//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloNuevoContainer : DbContext
    {
        public ModeloNuevoContainer()
            : base("name=ModeloNuevoContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Requerimiento> RequerimientoSet { get; set; }
        public virtual DbSet<Articulo> ArticuloSet { get; set; }
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<Grupo> GrupoSet { get; set; }
        public virtual DbSet<Rubro> RubroSet { get; set; }
        public virtual DbSet<DetalleCompra> DetalleCompraSet { get; set; }
        public virtual DbSet<Orden_Compra> Orden_CompraSet { get; set; }
        public virtual DbSet<Proveedor> ProveedorSet { get; set; }
        public virtual DbSet<Estados> EstadosSet { get; set; }
        public virtual DbSet<Remitos> Remitos { get; set; }
        public virtual DbSet<Comentarios> ComentariosSet { get; set; }
    }
}
